# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2676d396a4d794787fd5ace7119ccaf4724d48692d4e7aa7788b24cb5f9d2746df8f3b5bc446a3f3ee0b55c29ab9824d48accdaf02f8c2e2d44e58ef227fc5eb

test:
  secret_key_base: 6a29f8a38e7a6aee56f2c6947cd02f531647f129b2665f477d89ae8bb74cbef8a9effc21d2ea007d8dd4e981a005a3cd1be2a552a772794fc9dde73c422e1f64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
